import Lean4Lean.Theory.Typing.SpineVar
import Lean4Lean.Theory.Typing.RigidNodeCircle
import Lean4Lean.Theory.SetModel.Consts

/-!
# `ShapeIndepStep`: turning a context variable into a fresh axiom

The mechanics for `Theory/Typing/ShapeIndep.lean`, which answers the grading question
`docs/handoff-spinevar.md` §1.3/§4.1 left open: **do `SpineVarPiDisj`, `SpineVarSortDisj` and
`SpineVarAppDisj` follow from `RigidShapeUniq`?**

The instrument is one step of the standard "a context is a telescope of axioms" translation, in
the direction `Theory/Typing/ConstVar.lean` does *not* have.  `ConstVar.lean` transports a
judgement over `env.addConst c ci` down to `env` in a context extended by `ci.type` — constant to
variable.  This file goes the other way, and needs no new induction to do it, because one step is
exactly `IsDefEq.instN` at the **outermost** context entry:

* the outermost entry of an `OnCtx` context is typed in the empty context, hence closed;
* so it is a legal axiom type, and `env.addConst c ⟨U, T⟩` is well formed;
* so `.const c (VLevel.params U)` inhabits it over the extended environment;
* so `IsDefEq.instN` replaces `.bvar Γ''.length` by that constant, shortening the context by one.

Iterating shortens the context to `[]`, where every variable-headed row is already a theorem
(`SpineVar.lean` §7.1).  The iteration is in `ShapeIndep.lean`; here are the four ingredients.

## What this file does NOT do

It does not produce the fresh name.  `VEnv.WF` is `∃ ds, VEnv.WF' ds env`, so a well-formed
environment's constant table *is* generated by finitely many declarations and a fresh name does
exist; but extracting that needs a "names added" bound for every `VDecl.WF` arm, `addInduct'`
included, and none is in the tree.  So freshness is carried as an explicit hypothesis
(`VEnv.FreshNames`) and named in `ShapeIndep.lean`'s verdict as the one side condition.
-/

namespace Lean4Lean

open Lean (Name)

/-! ## §1 `spineHead` under instantiation

One `rfl`-induction.  Everything else in this file is bookkeeping around it. -/

/-- **Instantiation commutes with taking a spine head**, up to one more `spineHead` on the right:
the substituted term may itself be an application, so `instVar` can turn a variable head into a
spine.  The `.lam`/`.forallE` cases are `rfl` because a binder is its own spine head. -/
theorem VExpr.spineHead_inst : ∀ (e e₀ : VExpr) (k : Nat),
    (e.inst e₀ k).spineHead = (e.spineHead.inst e₀ k).spineHead
  | .app f _, e₀, k => VExpr.spineHead_inst f e₀ k
  | .bvar _, _, _ | .sort _, _, _ | .const .., _, _
  | .lam .., _, _ | .forallE .., _, _ => rfl

/-- A variable spine head **below** the substituted index survives as itself. -/
theorem VExpr.spineHead_inst_lt {e e₀ : VExpr} {i k : Nat}
    (hsh : e.spineHead = .bvar i) (h : i < k) : (e.inst e₀ k).spineHead = .bvar i := by
  rw [VExpr.spineHead_inst, hsh]; simp [VExpr.inst, VExpr.instVar, h, VExpr.spineHead]

/-- A variable spine head **at** the substituted index becomes the substituted term's. -/
theorem VExpr.spineHead_inst_eq {e e₀ : VExpr} {k : Nat}
    (hsh : e.spineHead = .bvar k) : (e.inst e₀ k).spineHead = (e₀.liftN k).spineHead := by
  rw [VExpr.spineHead_inst, hsh]; simp [VExpr.inst, VExpr.instVar]

/-- **Any term is its spine head applied to its spine.**  `PatternDecode.mkApp_spine` read
through `SpineVar.spine_fst_eq_spineHead`; the form the const rows want. -/
theorem VExpr.eq_spineHead_mkApp (e : VExpr) : e = e.spineHead.mkApp (VExpr.spine e).2 := by
  have h := VExpr.mkApp_spine e
  rw [VExpr.spine_fst_eq_spineHead] at h
  exact h.symm

/-- Instantiation distributes over an application spine. -/
theorem VExpr.mkApp_inst : ∀ (as : List VExpr) (f e₀ : VExpr) (k : Nat),
    (f.mkApp as).inst e₀ k = (f.inst e₀ k).mkApp (as.map (fun a => a.inst e₀ k))
  | [], _, _, _ => rfl
  | a :: as, f, e₀, k => VExpr.mkApp_inst as (.app f a) e₀ k

/-! ## §2 The outermost context entry -/

/-- The outermost entry of a well-formed context is typed in the **empty** context. -/
theorem OnCtx.last {P : List VExpr → VExpr → Prop} :
    ∀ {Γ : List VExpr} {T : VExpr}, OnCtx (Γ ++ [T]) P → P [] T
  | [], _, h => h.2
  | _ :: _, _, h => OnCtx.last h.1

/-- Substituting for the outermost variable is a `Ctx.InstN` at `Γ₀ = []`. -/
theorem Ctx.instN_last (e₀ : VExpr) : ∀ (Γ : List VExpr) (T : VExpr),
    ∃ Γ', Ctx.InstN [] e₀ T Γ.length (Γ ++ [T]) Γ' ∧ Γ'.length = Γ.length
  | [], _ => ⟨[], .zero, rfl⟩
  | A :: Γ, T =>
    let ⟨Γ', W, hl⟩ := Ctx.instN_last e₀ Γ T
    ⟨_, W.succ, by simp [hl]⟩

/-! ## §3 A fresh constant is rule-free, and adding it keeps the environment well formed -/

/-- A term's head constant is one of the constants it mentions. -/
theorem VExpr.ConstsIn.headConst? {P : Name → Prop} {c : Name} :
    ∀ {e : VExpr}, e.ConstsIn P → e.headConst? = some c → P c
  | .const _ _, h, hh => by cases hh; exact h
  | .app _ _, h, hh => VExpr.ConstsIn.headConst? h.1 hh
  | .lam _ _, h, hh => VExpr.ConstsIn.headConst? h.2 hh
  | .bvar _, _, hh | .sort _, _, hh | .forallE .., _, hh => absurd hh nofun

namespace VEnv

/-- **An undeclared constant heads no rule.**  Every rule's left-hand side is typed at its
staging environment, so it mentions only declared constants (`Ordered.constsInD`). -/
theorem ruleFreeHead_of_not_contains {env : VEnv} (hord : Ordered env) {c : Name}
    (hc : env.constants c = none) : env.RuleFreeHead c := fun df hdf hh => by
  obtain ⟨ci, hci⟩ := VExpr.ConstsIn.headConst? (hord.constsInD hdf).1 hh
  exact absurd hci (hc ▸ nofun)

/-- `RuleFreeHead` only mentions `env.defeqs`, which `addConst` does not touch. -/
theorem ruleFreeHead_addConst {env env' : VEnv} {n : Name} {ci : VConstant}
    (h : env.addConst n ci = some env') {c : Name} (hrf : env.RuleFreeHead c) :
    env'.RuleFreeHead c := fun df hdf => by
  refine hrf df ?_
  unfold VEnv.addConst at h; split at h <;> cases h; exact hdf

/-- Adding one axiom of well-formed type preserves `VEnv.WF`. -/
theorem wf_addConst {env env' : VEnv} {c : Name} {ci : VConstant} (henv : env.WF)
    (hci : VConstant.WF env ci) (h : env.addConst c ci = some env') : env'.WF :=
  let ⟨ds, hds⟩ := henv
  ⟨.axiom ⟨ci, c⟩ :: ds, .decl (.axiom hci h) hds⟩

/-- **A fresh-name supply.**  True of every `VEnv.WF` environment (its constant table is
generated by the finite declaration list `VEnv.WF'` carries), but not proved in this tree — see
the module docstring. -/
def FreshNames : Prop := ∀ env : VEnv, env.WF → ∃ c : Name, env.constants c = none

/-! ## §4 The step: one variable becomes one axiom -/

/-- **The axiomization step.**  Given a well-formed context `Γ ++ [T]`, a fresh name, and any
conversion over it, there is an environment one axiom bigger in which the conversion holds with
`.bvar Γ.length` replaced by that axiom, over a context one shorter.

Packaged as a single `∃` so `ShapeIndep.lean`'s three inductions can share it. -/
theorem axiomize_step {env : VEnv} {U : Nat} {Γ : List VExpr} {T : VExpr}
    (henv : env.WF) (hΓ : OnCtx (Γ ++ [T]) (env.IsType U)) {c : Name}
    (hfr : env.constants c = none) :
    ∃ (env' : VEnv) (Γ' : List VExpr),
      env ≤ env' ∧ env'.WF ∧ Γ'.length = Γ.length ∧ OnCtx Γ' (env'.IsType U) ∧
      env'.RuleFreeHead c ∧ (∀ c', env.RuleFreeHead c' → env'.RuleFreeHead c') ∧
      env'.HasType U [] (.const c (VLevel.params U)) T ∧
      Ctx.InstN [] (.const c (VLevel.params U)) T Γ.length (Γ ++ [T]) Γ' := by
  have hord := henv.ordered
  obtain ⟨u, hT⟩ : env.IsType U [] T := hΓ.last
  have hlwf : T.LevelWF U := (IsDefEq.levelWF hT trivial).1
  have hadd0 : env.addConst c ⟨U, T⟩ = some
      { constants := fun n => if c = n then some ⟨U, T⟩ else env.constants n,
        defeqs := env.defeqs } := by
    unfold VEnv.addConst; rw [hfr]
  obtain ⟨env', hadd⟩ : ∃ env', env.addConst c ⟨U, T⟩ = some env' := ⟨_, hadd0⟩
  obtain ⟨Γ', W, hlen⟩ := Ctx.instN_last (.const c (VLevel.params U)) Γ T
  have hle := addConst_le hadd
  have henv' := wf_addConst henv ⟨u, hT⟩ hadd
  have hord' := henv'.ordered
  have hconst : env'.HasType U [] (.const c (VLevel.params U)) T := by
    have h := VEnv.IsDefEq.constDF (env := env') (Γ := []) (uvars := U) (ls := VLevel.params U)
      (ls' := VLevel.params U) (addConst_self hadd) VLevel.params_wf VLevel.params_wf
      (by simp) (List.Forall₂.rfl fun _ _ => rfl)
    rwa [hlwf.instL_id] at h
  refine ⟨env', Γ', hle, henv', hlen, ?_, ?_, fun _ h => ruleFreeHead_addConst hadd h, hconst, W⟩
  · exact (Ctx.InstN.wf hord' W hconst (hΓ.mono fun h => h.mono hle)).2
  · exact ruleFreeHead_addConst hadd (ruleFreeHead_of_not_contains hord hfr)

end VEnv

section Audit
#print axioms Lean4Lean.VExpr.spineHead_inst
#print axioms Lean4Lean.VExpr.spineHead_inst_lt
#print axioms Lean4Lean.VExpr.spineHead_inst_eq
#print axioms Lean4Lean.VExpr.eq_spineHead_mkApp
#print axioms Lean4Lean.VExpr.mkApp_inst
#print axioms Lean4Lean.OnCtx.last
#print axioms Lean4Lean.Ctx.instN_last
#print axioms Lean4Lean.VExpr.ConstsIn.headConst?
#print axioms Lean4Lean.VEnv.ruleFreeHead_of_not_contains
#print axioms Lean4Lean.VEnv.ruleFreeHead_addConst
#print axioms Lean4Lean.VEnv.wf_addConst
#print axioms Lean4Lean.VEnv.axiomize_step
end Audit

end Lean4Lean
